apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-gen-certs
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-gen-certs
        tier: security
    spec:
      containers:
      - name: kube-gen-certs
        image: docker.astuart.co:5000/kube-gen-certs
        imagePullPolicy: Always
        command:
          - "go-wrapper"
          - "run"
          - "-incluster"
          - "-forcetls"
          - "-ttl=288h"
          - "-backend=vault"
        resources:
          requests:
            cpu: 250m
            memory: 500Mi
        env:
        - name: VAULT_ADDR
          valueFrom:
            configMapKeyRef:
              name: vault
              key: addr
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: vault-creds
              key: token
        - name: ROOT_CA
          valueFrom:
            secretKeyRef:
              name: stuart-ca
              key: ca.crt
        - name: EMAIL
          value: "andrew.stuart2@gmail.com"
        ports:
        - containerPort: 8080
        - containerPort: 8443
---
apiVersion: v1
kind: Service
metadata:
  name: kube-gen-certs
  namespace: kube-system
  labels:
    app: kube-gen-certs
    tier: security
spec:
  ports:
  - port: 443
    targetPort: 8443
  selector:
    app: kube-gen-certs
    tier: security
