apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: kube-systme
  name: kube-gen-certs
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-gen-certs
        tier: security
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: kube-gen-certs
        image: docker.astuart.co:5000/kube-gen-certs #Substitute your registry here
        imagePullPolicy: Always
        command:
          - "/kube-gen-certs"
          - "-incluster"
          - "-forcetls"
          - "-ttl=288h"
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
        env:
        - name: VAULT_ADDR
          valueFrom:
            configMapKeyRef:
              name: vault
              key: addr
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: vault-creds
              key: token
        - name: ROOT_CA
          valueFrom:
            secretKeyRef:
              name: ca
              key: ca.crt
        ports:
        - containerPort: 8080
